### ISSUE TITLE
Left PCB?

### ISSUE THREAD

**Issue by gorbachev** [Bastardkb/Scylla-PCB-Plate#5]
The project only includes the right-side PCB. Build guide has images of a left-side PCB with different silkscreen (e.g. "Left" printed on the PCB).

What's the process for fabricating a left-side PCB? Is it merely reversible? Or are there other changes required?

**Comment by bstiq** [comment]
Hi, 

All the PCBs are reversible yes, just order as is.
You can also open them in kicad to check yourself, the other side shows "left" just like you mentioned.

Regards,
